Feature/download opendata
Code-for-Funabashi/open_data_parser pull request #4
Opened 2021-05-10 14:40 UTC by Jumpo-523

とりあえず吐き出せるものは作りました。
5/11 の夜に、geocodeの結果の動作確認（前回のcoding結果との整合性）をします。

いろいろコード内でコメントしましたので、確認お願いいたしますー！（確認いただいた後消す予定です。）

2021-05-10 15:03 UTC, aca-ta requested changes
ちょっと実装難易度高い部分があるので、後で修正PRを出そうと思います。
不要になったファイルがいくつかあると思うので、そちらの削除だけお願いします 🙏

2021-05-10 15:03 UTC, aca-ta commented on open_data_parser/transformer.py
> +        # output_schemaで第一階層でkeyとして持つ情報以外は全てdetailedに入れちゃう仕様で作っている。
フロント側ではdetails内のパラメータはすべて任意項目で定義しているので、パーサーでは意識しなくて良いと思います。

https://github.com/Code-for-Funabashi/kosodate-map/blob/main/src/components/Points.tsx#L12-L15

2021-05-10 15:03 UTC, aca-ta commented on open_data_parser/scraper_and_geocode.py
> +from bs4 import BeautifulSoup
このファイルはいらなくなったはずなので削除してほしいです。

2021-05-10 15:06 UTC, aca-ta commented
@Jumpo-523 
実装上、議論したいポイントがある中でPRを出す場合は、ドラフトPRを出す+Githubのコメントで話したい事を書くと良いと思います。

2021-05-10 15:36 UTC, Jumpo-523 commented on open_data_parser/transformer.py
> +        # output_schemaで第一階層でkeyとして持つ情報以外は全てdetailedに入れちゃう仕様で作っている。
parser側は全部第一階層で渡しちゃっていいと言うことでしょうか？

2021-05-10 15:42 UTC, Jumpo-523 commented
> @Jumpo-523
> 実装上、議論したいポイントがある中でPRを出す場合は、ドラフトPRを出す+Githubのコメントで話したい事を書くと良いと思います。
確かに...承知しました！
`details`以外の修正完了しました。

2021-05-11 11:29 UTC, aca-ta commented
@Jumpo-523 
修正ありがとうございます！承認しました！

2021-05-15 13:13 UTC, merged